version: "3.7"
services:
  lifeseed-api:
    container_name: lifeseed-moon
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["8080:8080"]
    # depends_on:
    #   - "database"
    # volumes:
    #   - ./src:/var/service/src
    # networks:
    #   - bridgenet
    environment:
      NODE_ENV: "production"
      PORT: "8080"
      DATABASE_URL: $DATABASE_URL
      SESSION_SECRET: $SESSION_SECRET

